In [1]:
import zipfile
import json
import pandas as pd

NDC_ZIP = "drug-ndc-0001-of-0001.json.zip"

with zipfile.ZipFile(NDC_ZIP, "r") as z:
    print(z.namelist())

['drug-ndc-0001-of-0001.json']

In [3]:
with zipfile.ZipFile(NDC_ZIP, "r") as z:
    with z.open("drug-ndc-0001-of-0001.json") as f:
        ndc_data = json.load(f)

print(ndc_data.keys())
print("Number of NDC records:", len(ndc_data["results"]))

dict_keys(['meta', 'results'])
Number of NDC records: 138217

In [4]:
ndc = pd.json_normalize(ndc_data["results"])

print("Rows:", ndc.shape[0])
print("Columns:", ndc.shape[1])

ndc.head()

Rows: 138217
Columns: 32

,product_ndc,generic_name,labeler_name,brand_name,active_ingredients,finished,packaging,listing_expiration_date,marketing_category,dosage_form,...,openfda.unii,openfda.nui,openfda.pharm_class_pe,openfda.pharm_class_epc,openfda.pharm_class_cs,openfda.pharm_class_moa,marketing_end_date,dea_schedule,brand_name_suffix,openfda.upc
0,71288-432,Enoxaparin Sodium,Meitheal Pharmaceuticals Inc.,Enoxaparin Sodium,"[{'name': 'ENOXAPARIN SODIUM', 'strength': '10...",True,"[{'package_ndc': '71288-432-81', 'description'...",20261231,ANDA,INJECTION,...,[8NZ41MIK1O],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,71288-440,Desmopressin acetate,Meitheal Pharmaceuticals Inc.,Desmopressin acetate,"[{'name': 'DESMOPRESSIN ACETATE', 'strength': ...",True,"[{'package_ndc': '71288-440-02', 'description'...",20271231,ANDA,INJECTION,...,[XB13HYU18U],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,71288-441,Desmopressin acetate,Meitheal Pharmaceuticals Inc.,Desmopressin acetate,"[{'name': 'DESMOPRESSIN ACETATE', 'strength': ...",True,"[{'package_ndc': '71288-441-10', 'description'...",20271231,ANDA,INJECTION,...,[XB13HYU18U],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0409-0183,GEMCITABINE,"Hospira, Inc.",Gemcitabine,"[{'name': 'GEMCITABINE HYDROCHLORIDE', 'streng...",True,"[{'package_ndc': '0409-0183-01', 'description'...",20271231,NDA,"INJECTION, SOLUTION",...,[U347PV74IL],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,71288-450,Heparin Sodium,Meitheal Pharmaceuticals Inc.,Heparin Sodium,"[{'name': 'HEPARIN SODIUM', 'strength': '5000 ...",True,"[{'package_ndc': '71288-450-02', 'description'...",20261231,ANDA,INJECTION,...,[ZZ45AB24CA],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
ndc.info()
for column in ndc.columns:
    print(column)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138217 entries, 0 to 138216
Data columns (total 32 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   product_ndc                   138217 non-null  object
 1   generic_name                  138214 non-null  object
 2   labeler_name                  138217 non-null  object
 3   brand_name                    116474 non-null  object
 4   active_ingredients            135717 non-null  object
 5   finished                      138217 non-null  bool
 6   packaging                     138217 non-null  object
 7   listing_expiration_date       134331 non-null  object
 8   marketing_category            138217 non-null  object
 9   dosage_form                   138217 non-null  object
 10  spl_id                        138217 non-null  object
 11  product_type                  138217 non-null  object
 12  route                         114612 non-null  object
 13  marketing_start_date          138217 non-null  object
 14  product_id                    138217 non-null  object
 15  application_number            100107 non-null  object
 16  brand_name_base               116474 non-null  object
 17  pharm_class                   74358 non-null   object
 18  openfda.manufacturer_name     111504 non-null  object
 19  openfda.rxcui                 83426 non-null   object
 20  openfda.spl_set_id            111504 non-null  object
 21  openfda.is_original_packager  87549 non-null   object
 22  openfda.unii                  109562 non-null  object
 23  openfda.nui                   34497 non-null   object
 24  openfda.pharm_class_pe        14116 non-null   object
 25  openfda.pharm_class_epc       32384 non-null   object
 26  openfda.pharm_class_cs        17399 non-null   object
 27  openfda.pharm_class_moa       15727 non-null   object
 28  marketing_end_date            3879 non-null    object
 29  dea_schedule                  6330 non-null    object
 30  brand_name_suffix             8585 non-null    object
 31  openfda.upc                   38127 non-null   object
dtypes: bool(1), object(31)
memory usage: 32.8+ MB
product_ndc
generic_name
labeler_name
brand_name
active_ingredients
finished
packaging
listing_expiration_date
marketing_category
dosage_form
spl_id
product_type
route
marketing_start_date
product_id
application_number
brand_name_base
pharm_class
openfda.manufacturer_name
openfda.rxcui
openfda.spl_set_id
openfda.is_original_packager
openfda.unii
openfda.nui
openfda.pharm_class_pe
openfda.pharm_class_epc
openfda.pharm_class_cs
openfda.pharm_class_moa
marketing_end_date
dea_schedule
brand_name_suffix
openfda.upc

In [8]:
print("Total columns:", len(ndc.columns))

Total columns: 32

In [9]:
important_columns = [
    "product_ndc",
    "generic_name",
    "brand_name",
    "labeler_name",
    "dosage_form",
    "route",
    "marketing_category",
    "marketing_start_date",
    "marketing_end_date",
    "packaging"
]

existing_columns = [
    col for col in important_columns
    if col in ndc.columns
]

ndc[existing_columns].head(10)

,product_ndc,generic_name,brand_name,labeler_name,dosage_form,route,marketing_category,marketing_start_date,marketing_end_date,packaging
0,71288-432,Enoxaparin Sodium,Enoxaparin Sodium,Meitheal Pharmaceuticals Inc.,INJECTION,[SUBCUTANEOUS],ANDA,20191201,NaN,"[{'package_ndc': '71288-432-81', 'description'..."
1,71288-440,Desmopressin acetate,Desmopressin acetate,Meitheal Pharmaceuticals Inc.,INJECTION,"[INTRAVENOUS, SUBCUTANEOUS]",ANDA,20260213,NaN,"[{'package_ndc': '71288-440-02', 'description'..."
2,71288-441,Desmopressin acetate,Desmopressin acetate,Meitheal Pharmaceuticals Inc.,INJECTION,"[INTRAVENOUS, SUBCUTANEOUS]",ANDA,20260213,NaN,"[{'package_ndc': '71288-441-10', 'description'..."
3,0409-0183,GEMCITABINE,Gemcitabine,"Hospira, Inc.","INJECTION, SOLUTION",[INTRAVENOUS],NDA,20110824,NaN,"[{'package_ndc': '0409-0183-01', 'description'..."
4,71288-450,Heparin Sodium,Heparin Sodium,Meitheal Pharmaceuticals Inc.,INJECTION,"[INTRAVENOUS, SUBCUTANEOUS]",ANDA,20250702,NaN,"[{'package_ndc': '71288-450-02', 'description'..."
5,71288-451,Heparin Sodium,Heparin Sodium,Meitheal Pharmaceuticals Inc.,INJECTION,"[INTRAVENOUS, SUBCUTANEOUS]",ANDA,20250702,NaN,"[{'package_ndc': '71288-451-02', 'description'..."
6,71288-716,Methocarbamol,Methocarbamol,Meitheal Pharmaceuticals Inc.,"INJECTION, SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]",ANDA,20181217,NaN,"[{'package_ndc': '71288-716-10', 'description'..."
7,71288-734,Ropivacaine Hydrochloride,Ropivacaine Hydrochloride,Meitheal Pharmaceuticals Inc.,"INJECTION, SOLUTION","[EPIDURAL, INFILTRATION, PERINEURAL]",ANDA,20240730,NaN,"[{'package_ndc': '71288-734-21', 'description'..."
8,71288-736,Ropivacaine Hydrochloride,Ropivacaine Hydrochloride,Meitheal Pharmaceuticals Inc.,"INJECTION, SOLUTION","[EPIDURAL, PERINEURAL]",ANDA,20240730,NaN,"[{'package_ndc': '71288-736-21', 'description'..."
9,71288-811,Methylene Blue,Methylene Blue,Meitheal Pharmaceuticals Inc.,INJECTION,[INTRAVENOUS],ANDA,20250123,NaN,"[{'package_ndc': '71288-811-11', 'description'..."

In [13]:
ndc["packaging"].iloc[0]

[{'package_ndc': '71288-432-81',
  'description': '10 SYRINGE in 1 CARTON (71288-432-81)  / .3 mL in 1 SYRINGE (71288-432-80)',
  'marketing_start_date': '20191201',
  'sample': False}]

In [14]:
type(ndc["packaging"].iloc[0])

list

In [15]:
package_rows = []

for index, row in ndc.iterrows():

    packages = row.get("packaging")

    if not isinstance(packages, list):
        continue

    for package in packages:

        if not isinstance(package, dict):
            continue

        package_rows.append({
            "product_ndc": row.get("product_ndc"),
            "generic_name": row.get("generic_name"),
            "brand_name": row.get("brand_name"),
            "labeler_name": row.get("labeler_name"),
            "package_ndc": package.get("package_ndc"),
            "package_description": package.get("description")
        })


packages = pd.DataFrame(package_rows)

print("Package records:", len(packages))

packages.head()

Package records: 256387

,product_ndc,generic_name,brand_name,labeler_name,package_ndc,package_description
0,71288-432,Enoxaparin Sodium,Enoxaparin Sodium,Meitheal Pharmaceuticals Inc.,71288-432-81,10 SYRINGE in 1 CARTON (71288-432-81) / .3 mL...
1,71288-440,Desmopressin acetate,Desmopressin acetate,Meitheal Pharmaceuticals Inc.,71288-440-02,10 VIAL in 1 CARTON (71288-440-02) / 1 mL in ...
2,71288-441,Desmopressin acetate,Desmopressin acetate,Meitheal Pharmaceuticals Inc.,71288-441-10,1 VIAL in 1 CARTON (71288-441-10) / 10 mL in ...
3,0409-0183,GEMCITABINE,Gemcitabine,"Hospira, Inc.",0409-0183-01,"1 VIAL, SINGLE-DOSE in 1 CARTON (0409-0183-01)..."
4,71288-450,Heparin Sodium,Heparin Sodium,Meitheal Pharmaceuticals Inc.,71288-450-02,"25 VIAL, MULTI-DOSE in 1 CARTON (71288-450-02)..."

In [16]:
print("Total package rows:", len(packages))

print(
    "Unique package NDCs:",
    packages["package_ndc"].nunique()
)

print(
    "Missing package NDCs:",
    packages["package_ndc"].isna().sum()
)

print(
    "Duplicate package NDC rows:",
    packages["package_ndc"].duplicated().sum()
)

Total package rows: 256387
Unique package NDCs: 256383
Missing package NDCs: 0
Duplicate package NDC rows: 4

In [17]:
missing = pd.DataFrame({
    "Missing_Count": ndc.isna().sum(),
    "Missing_Percent":
        (ndc.isna().sum() / len(ndc) * 100).round(2)
})

missing.sort_values(
    "Missing_Percent",
    ascending=False
)

                              Missing_Count  Missing_Percent
marketing_end_date                   134338            97.19
dea_schedule                         131887            95.42
brand_name_suffix                    129632            93.79
openfda.pharm_class_pe               124101            89.79
openfda.pharm_class_moa              122490            88.62
openfda.pharm_class_cs               120818            87.41
openfda.pharm_class_epc              105833            76.57
openfda.nui                          103720            75.04
openfda.upc                          100090            72.42
pharm_class                           63859            46.20
openfda.rxcui                         54791            39.64
openfda.is_original_packager          50668            36.66
application_number                    38110            27.57
openfda.unii                          28655            20.73
openfda.manufacturer_name             26713            19.33
openfda.spl_set_id                    26713            19.33
route                                 23605            17.08
brand_name                            21743            15.73
brand_name_base                       21743            15.73
listing_expiration_date                3886             2.81
active_ingredients                     2500             1.81
product_id                                0             0.00
spl_id                                    0             0.00
marketing_start_date                      0             0.00
product_ndc                               0             0.00
labeler_name                              0             0.00
generic_name                              3             0.00
product_type                              0             0.00
dosage_form                               0             0.00
marketing_category                        0             0.00
finished                                  0             0.00
packaging                                 0             0.00