In [1]:
import zipfile
import json
import pandas as pd

RECALL_ZIP = "drug-enforcement-0001-of-0001.json.zip"

with zipfile.ZipFile(RECALL_ZIP, "r") as z:
    print(z.namelist())

['drug-enforcement-0001-of-0001.json']

In [2]:
with zipfile.ZipFile(RECALL_ZIP, "r") as z:
    json_file = z.namelist()[0]

    with z.open(json_file) as f:
        recall_data = json.load(f)

print(recall_data.keys())
print("Number of recall records:", len(recall_data["results"]))

dict_keys(['meta', 'results'])
Number of recall records: 17975

In [3]:
recalls = pd.json_normalize(recall_data["results"])

print("Rows:", recalls.shape[0])
print("Columns:", recalls.shape[1])

recalls.head()

Rows: 17975
Columns: 45

,status,city,state,country,classification,product_type,event_id,recalling_firm,address_1,address_2,...,openfda.upc,openfda.nui,openfda.pharm_class_moa,openfda.pharm_class_epc,openfda.unii,termination_date,more_code_info,openfda.pharm_class_cs,openfda.pharm_class_pe,openfda.original_packager_product_ndc
0,Ongoing,Woburn,MA,United States,Not Yet Classified,Drugs,99666,"Safecor Health, LLC",317 New Boston St,N/A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ongoing,"Sinnar, Nashik District",N/A,India,Class II,Drugs,81707,"Mylan Laboratories Limited, (Nashik FDF)","F-4 F-12, Malegaon M.I.D.C., Sinnar",N/A,...,"[0303781722933, 0303781723930, 0303781721936, ...","[N0000000070, N0000175561]",[Angiotensin 2 Receptor Antagonists [MoA]],[Angiotensin 2 Receptor Blocker [EPC]],"[80M03YXJ7I, 864V2Q084H]",NaN,NaN,NaN,NaN,NaN
2,Terminated,Sellersville,PA,United States,Class III,Drugs,64644,"Teva Pharmaceuticals USA, Inc.",650 Cathill Rd,N/A,...,NaN,"[N0000175825, N0000000100]",[Estrogen Receptor Agonists [MoA]],[Estrogen [EPC]],"[9S44LIC7OJ, 423D2T571U]",20140410,NaN,NaN,NaN,NaN
3,Ongoing,Ledgewood,NJ,United States,Class III,Drugs,99756,ImprimisRx NJ LLC,1705 Us Highway 46 Ste 4,,...,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
4,Ongoing,Deerfield,IL,United States,Class II,Drugs,99500,Baxter Healthcare Corporation,1 Baxter Pkwy,N/A,...,NaN,NaN,NaN,NaN,[976728SY6Z],NaN,,NaN,NaN,NaN

In [4]:
for column in recalls.columns:
    print(column)

status
city
state
country
classification
product_type
event_id
recalling_firm
address_1
address_2
postal_code
voluntary_mandated
initial_firm_notification
distribution_pattern
recall_number
product_description
product_quantity
reason_for_recall
recall_initiation_date
report_date
code_info
center_classification_date
openfda.application_number
openfda.brand_name
openfda.generic_name
openfda.manufacturer_name
openfda.product_ndc
openfda.product_type
openfda.route
openfda.substance_name
openfda.rxcui
openfda.spl_id
openfda.spl_set_id
openfda.package_ndc
openfda.is_original_packager
openfda.upc
openfda.nui
openfda.pharm_class_moa
openfda.pharm_class_epc
openfda.unii
termination_date
more_code_info
openfda.pharm_class_cs
openfda.pharm_class_pe
openfda.original_packager_product_ndc

In [5]:
recalls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17975 entries, 0 to 17974
Data columns (total 45 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   status                                 17975 non-null  object
 1   city                                   17975 non-null  object
 2   state                                  17975 non-null  object
 3   country                                17975 non-null  object
 4   classification                         17975 non-null  object
 5   product_type                           17975 non-null  object
 6   event_id                               17975 non-null  object
 7   recalling_firm                         17975 non-null  object
 8   address_1                              17975 non-null  object
 9   address_2                              17975 non-null  object
 10  postal_code                            17975 non-null  object
 11  voluntary_mandated                     17975 non-null  object
 12  initial_firm_notification              17975 non-null  object
 13  distribution_pattern                   17975 non-null  object
 14  recall_number                          17975 non-null  object
 15  product_description                    17975 non-null  object
 16  product_quantity                       17975 non-null  object
 17  reason_for_recall                      17975 non-null  object
 18  recall_initiation_date                 17975 non-null  object
 19  report_date                            17975 non-null  object
 20  code_info                              17975 non-null  object
 21  center_classification_date             17973 non-null  object
 22  openfda.application_number             3174 non-null   object
 23  openfda.brand_name                     3236 non-null   object
 24  openfda.generic_name                   3236 non-null   object
 25  openfda.manufacturer_name              3236 non-null   object
 26  openfda.product_ndc                    3236 non-null   object
 27  openfda.product_type                   3236 non-null   object
 28  openfda.route                          3185 non-null   object
 29  openfda.substance_name                 3167 non-null   object
 30  openfda.rxcui                          3117 non-null   object
 31  openfda.spl_id                         3236 non-null   object
 32  openfda.spl_set_id                     3236 non-null   object
 33  openfda.package_ndc                    3236 non-null   object
 34  openfda.is_original_packager           3047 non-null   object
 35  openfda.upc                            1546 non-null   object
 36  openfda.nui                            1142 non-null   object
 37  openfda.pharm_class_moa                574 non-null    object
 38  openfda.pharm_class_epc                1090 non-null   object
 39  openfda.unii                           3170 non-null   object
 40  termination_date                       14806 non-null  object
 41  more_code_info                         8365 non-null   object
 42  openfda.pharm_class_cs                 553 non-null    object
 43  openfda.pharm_class_pe                 366 non-null    object
 44  openfda.original_packager_product_ndc  191 non-null    object
dtypes: object(45)
memory usage: 6.2+ MB

In [6]:
recalls["classification"].value_counts(dropna=False)

classification
Class II              14511
Class I                1747
Class III              1715
Not Yet Classified        2
Name: count, dtype: int64

In [7]:
recalls["status"].value_counts(dropna=False)

status
Terminated    14803
Ongoing        2736
Completed       436
Name: count, dtype: int64

In [8]:
recalls["recalling_firm"].value_counts().head(20)

recalling_firm
Aidapak Services, LLC                                              538
Attix Pharmaceuticals                                              470
King Bio Inc.                                                      465
The Compounding Pharmacy of America                                383
Main Street Family Pharmacy, LLC                                   299
Central Admixture Pharmacy Services, Inc.                          275
Pharmedium Services, LLC                                           246
Cardinal Health Inc.                                               213
Franck's Lab Inc., d.b.a. Franck's Compounding Lab                 198
Teva Pharmaceuticals USA                                           196
Akorn, Inc.                                                        175
Dr. Reddy's Laboratories, Inc.                                     163
Mckesson Medical-Surgical Inc. Corporate Office                    157
Glenmark Pharmaceuticals Inc., USA                                 141
First Royal Care Co. LLC, dba Red Mountain Compounding Pharmacy    140
Hospira Inc.                                                       138
Altaire Pharmaceuticals, Inc.                                      135
Vita Pharmacy, LLC dba Talon Compounding Pharmacy                  130
KRS Global Biotechnology, Inc                                      129
Lupin Pharmaceuticals Inc.                                         123
Name: count, dtype: int64

In [9]:
recalls[
    [
        "recalling_firm",
        "classification",
        "product_description",
        "reason_for_recall"
    ]
].head(10)

,recalling_firm,classification,product_description,reason_for_recall
0,"Safecor Health, LLC",Not Yet Classified,"Ibuprofen, 150 mg per 7.5 mL, Delivers: 7.5 mL...",Cross Contamination with Other Products
1,"Mylan Laboratories Limited, (Nashik FDF)",Class II,"Amlodipine and Valsartan Tablets, USP 10/160 m...",GCMP Deviations: FDA analysis confirmed presen...
2,"Teva Pharmaceuticals USA, Inc.",Class III,Junel(TM) Fe 1.5/30 (norethindrone acetate and...,Failed Impurity/Degradation Specification; an ...
3,ImprimisRx NJ LLC,Class III,Povidone Iodine 1.25% / Proparacaine HCl 0.5% ...,Subpotent Drug
4,Baxter Healthcare Corporation,Class II,"Nexterone (amiodarone HCI), 360 mg/200 mL (1.8...",CGMP Deviations
5,AbbVie Inc,Class II,"CREON (pancrelipase) Delayed-Release Capsules,...",Presence of Foreign Tablets/Capsules; Presence...
6,Baxter Healthcare Corporation,Class I,"Dextrose Injection, USP, 70 %, 2000 mL bags, R...",Presence of Particulate Matter: particulate ma...
7,"Teva Pharmaceuticals USA, Inc",Class II,"traZODone Hydrochloride Tablets, USP, 50 mg, R...",Presence of Foreign Tablets/Capsules
8,Aurobindo Pharma USA Inc.,Class III,"Amlodipine and Olmesartan Medoxomil Tablets, 5...",Discoloration: This product is being recalled ...
9,Ajanta Pharma USA Inc,Class III,"Fluphenazine Hydrochloride Tablets, USP, 1mg, ...",Failed impurities/degradation specifications: ...

In [10]:
print(recalls["reason_for_recall"].dropna().iloc[0])

Cross Contamination with Other Products

In [2]:
import pandas as pd
import json
import zipfile

In [3]:
with zipfile.ZipFile("drug-enforcement-0001-of-0001.json.zip", "r") as z:
    json_file = z.namelist()[0]

    with z.open(json_file) as f:
        recall_data = json.load(f)

recalls = pd.json_normalize(recall_data["results"])

print("Rows:", recalls.shape[0])
print("Columns:", recalls.shape[1])

recalls.head()

Rows: 17975
Columns: 45

,status,city,state,country,classification,product_type,event_id,recalling_firm,address_1,address_2,...,openfda.upc,openfda.nui,openfda.pharm_class_moa,openfda.pharm_class_epc,openfda.unii,termination_date,more_code_info,openfda.pharm_class_cs,openfda.pharm_class_pe,openfda.original_packager_product_ndc
0,Ongoing,Woburn,MA,United States,Not Yet Classified,Drugs,99666,"Safecor Health, LLC",317 New Boston St,N/A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ongoing,"Sinnar, Nashik District",N/A,India,Class II,Drugs,81707,"Mylan Laboratories Limited, (Nashik FDF)","F-4 F-12, Malegaon M.I.D.C., Sinnar",N/A,...,"[0303781722933, 0303781723930, 0303781721936, ...","[N0000000070, N0000175561]",[Angiotensin 2 Receptor Antagonists [MoA]],[Angiotensin 2 Receptor Blocker [EPC]],"[80M03YXJ7I, 864V2Q084H]",NaN,NaN,NaN,NaN,NaN
2,Terminated,Sellersville,PA,United States,Class III,Drugs,64644,"Teva Pharmaceuticals USA, Inc.",650 Cathill Rd,N/A,...,NaN,"[N0000175825, N0000000100]",[Estrogen Receptor Agonists [MoA]],[Estrogen [EPC]],"[9S44LIC7OJ, 423D2T571U]",20140410,NaN,NaN,NaN,NaN
3,Ongoing,Ledgewood,NJ,United States,Class III,Drugs,99756,ImprimisRx NJ LLC,1705 Us Highway 46 Ste 4,,...,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
4,Ongoing,Deerfield,IL,United States,Class II,Drugs,99500,Baxter Healthcare Corporation,1 Baxter Pkwy,N/A,...,NaN,NaN,NaN,NaN,[976728SY6Z],NaN,,NaN,NaN,NaN

In [4]:
missing = pd.DataFrame({
    "Missing_Count": recalls.isna().sum(),
    "Missing_Percent":
        (recalls.isna().sum() / len(recalls) * 100).round(2)
})

missing.sort_values(
    "Missing_Percent",
    ascending=False
)

                                       Missing_Count  Missing_Percent
openfda.original_packager_product_ndc          17784            98.94
openfda.pharm_class_pe                         17609            97.96
openfda.pharm_class_cs                         17422            96.92
openfda.pharm_class_moa                        17401            96.81
openfda.pharm_class_epc                        16885            93.94
openfda.nui                                    16833            93.65
openfda.upc                                    16429            91.40
openfda.is_original_packager                   14928            83.05
openfda.rxcui                                  14858            82.66
openfda.substance_name                         14808            82.38
openfda.unii                                   14805            82.36
openfda.application_number                     14801            82.34
openfda.route                                  14790            82.28
openfda.package_ndc                            14739            82.00
openfda.product_ndc                            14739            82.00
openfda.generic_name                           14739            82.00
openfda.spl_id                                 14739            82.00
openfda.spl_set_id                             14739            82.00
openfda.manufacturer_name                      14739            82.00
openfda.brand_name                             14739            82.00
openfda.product_type                           14739            82.00
more_code_info                                  9610            53.46
termination_date                                3169            17.63
center_classification_date                         2             0.01
classification                                     0             0.00
status                                             0             0.00
country                                            0             0.00
state                                              0             0.00
city                                               0             0.00
initial_firm_notification                          0             0.00
voluntary_mandated                                 0             0.00
postal_code                                        0             0.00
address_2                                          0             0.00
address_1                                          0             0.00
recalling_firm                                     0             0.00
event_id                                           0             0.00
product_type                                       0             0.00
distribution_pattern                               0             0.00
recall_number                                      0             0.00
product_description                                0             0.00
product_quantity                                   0             0.00
reason_for_recall                                  0             0.00
recall_initiation_date                             0             0.00
report_date                                        0             0.00
code_info                                          0             0.00

In [6]:
date_columns = [
    "recall_initiation_date",
    "report_date",
    "termination_date"
]

for column in date_columns:

    if column in recalls.columns:

        print("\n", column)
        print(recalls[column].head())

 recall_initiation_date
0    20260814
1    20181204
2    20130315
3    20260824
4    20260806
Name: recall_initiation_date, dtype: object

 report_date
0    20260902
1    20181219
2    20130717
3    20260916
4    20260909
Name: report_date, dtype: object

 termination_date
0         NaN
1         NaN
2    20140410
3         NaN
4         NaN
Name: termination_date, dtype: object